<MyLayout>
    BoxLayout:

        orientation: 'vertical'
        size: root.width, root.height

        Carousel:
            direction: "right"

            Image:
                source: "love/iloveu.jpg"
            AsyncImage:
                source: "https://i.pinimg.com/originals/20/33/4a/20334a28129f1b37cde358b6204875f6.jpg"

            Label:
                text: "love"
                font_size: 32
