<MyLayout>
    BoxLayout:

        orientation: 'vertical'
        size: root.width, root.height

        Label:
            id: click_label
            text: "below"
            gont_size: 32
        
        Spinner:
            id: spinner_id
            text: "favorite pizza"
            values: ["Prpperoni", "cheese", "meat", "heam"]

            on_text: root.spinner_clicked(spinner_id.text)
             
        Label:
            text: " "