<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width , root.height

        spacing: 20
        padding: 30

        Image:
            source: 'love/iloveu.jpg'
            allow_stretch: True
            keep_ratio: True
        Button:
            text: "hello world"

        Button:
            text: "node world"
        
        Button:
            text: "bye world"


        