<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width , root.height

        Button:
            text: "hello world"
            pos_hint: {'center_x': 0.5}
            size_hint: (None,None)
            width:50
            height:100
        
        Button:
            text: "node world"
        
        Button:
            text: "bye world"

            

        